// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic.model.dod;

import com.springsource.petclinic.model.dod.DataOnDemandConfiguration;
import com.springsource.petclinic.model.dod.OwnerDataOnDemand;
import com.springsource.petclinic.model.dod.PetDataOnDemand;
import com.springsource.petclinic.model.dod.VetDataOnDemand;
import com.springsource.petclinic.model.dod.VisitDataOnDemand;
import javax.persistence.EntityManager;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;

privileged aspect DataOnDemandConfiguration_Roo_JpaDataOnDemandConfiguration {
    
    declare @type: DataOnDemandConfiguration: @TestConfiguration;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private EntityManager DataOnDemandConfiguration.entityManager;
    
    /**
     * TODO Auto-generated constructor documentation
     * 
     * @param entityManager
     */
    @Autowired
    public DataOnDemandConfiguration.new(EntityManager entityManager) {
        setEntityManager(entityManager);
    }

    /**
     * TODO Auto-generated method documentation
     * 
     * @return EntityManager
     */
    public EntityManager DataOnDemandConfiguration.getEntityManager() {
        return entityManager;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entityManager
     */
    public void DataOnDemandConfiguration.setEntityManager(EntityManager entityManager) {
        this.entityManager = entityManager;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return OwnerDataOnDemand
     */
    @Bean
    public OwnerDataOnDemand DataOnDemandConfiguration.ownerDataOnDemand() {
        return new OwnerDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return PetDataOnDemand
     */
    @Bean
    public PetDataOnDemand DataOnDemandConfiguration.petDataOnDemand() {
        return new PetDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return VetDataOnDemand
     */
    @Bean
    public VetDataOnDemand DataOnDemandConfiguration.vetDataOnDemand() {
        return new VetDataOnDemand(getEntityManager());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return VisitDataOnDemand
     */
    @Bean
    public VisitDataOnDemand DataOnDemandConfiguration.visitDataOnDemand() {
        return new VisitDataOnDemand(getEntityManager());
    }
    
}
