// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic.model.dod;

import com.springsource.petclinic.model.Owner;
import com.springsource.petclinic.model.Pet;
import com.springsource.petclinic.model.dod.PetFactory;
import com.springsource.petclinic.model.reference.PetType;

privileged aspect PetFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Pet} with the given index.
     * 
     * @param index position of the Pet
     * @return a new transient Pet
     */
    public Pet PetFactory.create(int index) {
        Pet obj = new Pet();
        setName(obj, index);
        setOwner(obj, index);
        setSendReminders(obj, index);
        setType(obj, index);
        setWeight(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void PetFactory.setName(Pet obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void PetFactory.setOwner(Pet obj, int index) {
        Owner owner = null;
        obj.setOwner(owner);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void PetFactory.setSendReminders(Pet obj, int index) {
        Boolean sendReminders = true;
        obj.setSendReminders(sendReminders);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void PetFactory.setType(Pet obj, int index) {
        PetType type = PetType.class.getEnumConstants()[0];
        obj.setType(type);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void PetFactory.setWeight(Pet obj, int index) {
        Float weight = new Integer(index).floatValue();
        obj.setWeight(weight);
    }
    
}
