// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic.model;

import com.springsource.petclinic.model.PetTest;
import com.springsource.petclinic.model.dod.PetFactory;

privileged aspect PetTest_Roo_JpaUnitTest {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private PetFactory PetTest.petFactory = new PetFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return PetFactory
     */
    public PetFactory PetTest.getPetFactory() {
        return petFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param petFactory
     */
    public void PetTest.setPetFactory(PetFactory petFactory) {
        this.petFactory = petFactory;
    }
    
}
