// Generated by delombok at Wed Jul 31 07:36:11 MSK 2019
/*
 * Copyright 2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package example.springdata.r2dbc.basics;

import lombok.NonNull;
import reactor.core.publisher.Mono;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * @author Oliver Drotbohm
 */
@Component
class TransactionalService {
	@NonNull
	private final CustomerRepository repository;

	/**
	 * Saves the given {@link Customer} unless its firstname is "Dave".
	 *
	 * @param customer must not be {@literal null}.
	 * @return
	 */
	@Transactional
	public Mono<Customer> save(Customer customer) {
		return repository.save(customer).map(it -> {
			if (it.firstname.equals("Dave")) {
				throw new IllegalStateException();
			} else {
				return it;
			}
		});
	}

	@SuppressWarnings("all")
	public TransactionalService(@NonNull final CustomerRepository repository) {
		if (repository == null) {
			throw new NullPointerException("repository is marked non-null but is null");
		}
		this.repository = repository;
	}
}
