// Generated by delombok at Tue Jul 30 22:25:10 MSK 2019
/*
 * Copyright 2014-2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package example.springdata.mongodb.customer;

import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.util.Assert;

/**
 * An entity to represent a customer.
 *
 * @author Oliver Gierke
 */
@Document
public class Customer {
	private String id;
	private String firstname;
	private String lastname;
	private Address address;

	/**
	 * Creates a new {@link Customer} with the given firstname and lastname.
	 *
	 * @param firstname must not be {@literal null} or empty.
	 * @param lastname must not be {@literal null} or empty.
	 */
	public Customer(String firstname, String lastname) {
		Assert.hasText(firstname, "Firstname must not be null or empty!");
		Assert.hasText(lastname, "Lastname must not be null or empty!");
		this.firstname = firstname;
		this.lastname = lastname;
	}

	@SuppressWarnings("all")
	public String getId() {
		return this.id;
	}

	@SuppressWarnings("all")
	public String getFirstname() {
		return this.firstname;
	}

	@SuppressWarnings("all")
	public String getLastname() {
		return this.lastname;
	}

	@SuppressWarnings("all")
	public Address getAddress() {
		return this.address;
	}

	@SuppressWarnings("all")
	public void setId(final String id) {
		this.id = id;
	}

	@SuppressWarnings("all")
	public void setFirstname(final String firstname) {
		this.firstname = firstname;
	}

	@SuppressWarnings("all")
	public void setLastname(final String lastname) {
		this.lastname = lastname;
	}

	@SuppressWarnings("all")
	public void setAddress(final Address address) {
		this.address = address;
	}

	@Override
	@SuppressWarnings("all")
	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof Customer)) return false;
		final Customer other = (Customer) o;
		if (!other.canEqual((Object) this)) return false;
		final Object this$id = this.getId();
		final Object other$id = other.getId();
		if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
		final Object this$firstname = this.getFirstname();
		final Object other$firstname = other.getFirstname();
		if (this$firstname == null ? other$firstname != null : !this$firstname.equals(other$firstname)) return false;
		final Object this$lastname = this.getLastname();
		final Object other$lastname = other.getLastname();
		if (this$lastname == null ? other$lastname != null : !this$lastname.equals(other$lastname)) return false;
		final Object this$address = this.getAddress();
		final Object other$address = other.getAddress();
		if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
		return true;
	}

	@SuppressWarnings("all")
	protected boolean canEqual(final Object other) {
		return other instanceof Customer;
	}

	@Override
	@SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $id = this.getId();
		result = result * PRIME + ($id == null ? 43 : $id.hashCode());
		final Object $firstname = this.getFirstname();
		result = result * PRIME + ($firstname == null ? 43 : $firstname.hashCode());
		final Object $lastname = this.getLastname();
		result = result * PRIME + ($lastname == null ? 43 : $lastname.hashCode());
		final Object $address = this.getAddress();
		result = result * PRIME + ($address == null ? 43 : $address.hashCode());
		return result;
	}

	@Override
	@SuppressWarnings("all")
	public String toString() {
		return "Customer(id=" + this.getId() + ", firstname=" + this.getFirstname() + ", lastname=" + this.getLastname() + ", address=" + this.getAddress() + ")";
	}
}
