// Generated by delombok at Tue Jul 30 22:24:37 MSK 2019
/*
 * Copyright 2015-2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package example.springdata.jpa.projections;

/**
 * @author Oliver Gierke
 */
public class CustomerDto {
	private final String firstname;

	@SuppressWarnings("all")
	public String getFirstname() {
		return this.firstname;
	}

	@Override
	@SuppressWarnings("all")
	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof CustomerDto)) return false;
		final CustomerDto other = (CustomerDto) o;
		if (!other.canEqual((Object) this)) return false;
		final Object this$firstname = this.getFirstname();
		final Object other$firstname = other.getFirstname();
		if (this$firstname == null ? other$firstname != null : !this$firstname.equals(other$firstname)) return false;
		return true;
	}

	@SuppressWarnings("all")
	protected boolean canEqual(final Object other) {
		return other instanceof CustomerDto;
	}

	@Override
	@SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $firstname = this.getFirstname();
		result = result * PRIME + ($firstname == null ? 43 : $firstname.hashCode());
		return result;
	}

	@Override
	@SuppressWarnings("all")
	public String toString() {
		return "CustomerDto(firstname=" + this.getFirstname() + ")";
	}

	@SuppressWarnings("all")
	public CustomerDto(final String firstname) {
		this.firstname = firstname;
	}
}
