// Generated by delombok at Tue Jul 30 22:24:37 MSK 2019
/*
 * Copyright 2015-2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package example.springdata.jpa.projections;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * @author Oliver Gierke
 */
@Entity
public class Customer {
	@GeneratedValue
	@Id
	private Long id;
	private final String firstname;
	private final String lastname;

	protected Customer() {
		this.firstname = null;
		this.lastname = null;
	}

	@SuppressWarnings("all")
	public Long getId() {
		return this.id;
	}

	@SuppressWarnings("all")
	public String getFirstname() {
		return this.firstname;
	}

	@SuppressWarnings("all")
	public String getLastname() {
		return this.lastname;
	}

	@SuppressWarnings("all")
	public void setId(final Long id) {
		this.id = id;
	}

	@Override
	@SuppressWarnings("all")
	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof Customer)) return false;
		final Customer other = (Customer) o;
		if (!other.canEqual((Object) this)) return false;
		final Object this$id = this.getId();
		final Object other$id = other.getId();
		if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
		final Object this$firstname = this.getFirstname();
		final Object other$firstname = other.getFirstname();
		if (this$firstname == null ? other$firstname != null : !this$firstname.equals(other$firstname)) return false;
		final Object this$lastname = this.getLastname();
		final Object other$lastname = other.getLastname();
		if (this$lastname == null ? other$lastname != null : !this$lastname.equals(other$lastname)) return false;
		return true;
	}

	@SuppressWarnings("all")
	protected boolean canEqual(final Object other) {
		return other instanceof Customer;
	}

	@Override
	@SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $id = this.getId();
		result = result * PRIME + ($id == null ? 43 : $id.hashCode());
		final Object $firstname = this.getFirstname();
		result = result * PRIME + ($firstname == null ? 43 : $firstname.hashCode());
		final Object $lastname = this.getLastname();
		result = result * PRIME + ($lastname == null ? 43 : $lastname.hashCode());
		return result;
	}

	@Override
	@SuppressWarnings("all")
	public String toString() {
		return "Customer(id=" + this.getId() + ", firstname=" + this.getFirstname() + ", lastname=" + this.getLastname() + ")";
	}

	@SuppressWarnings("all")
	public Customer(final String firstname, final String lastname) {
		this.firstname = firstname;
		this.lastname = lastname;
	}
}
