// Generated by delombok at Tue Jul 30 22:24:37 MSK 2019
/*
 * Copyright 2017-2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package example.springdata.jpa.compositions;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import org.springframework.data.jpa.domain.AbstractPersistable;

/**
 * Sample user class.
 *
 * @author Mark Paluch
 */
@Entity
public class User extends AbstractPersistable<Long> implements Contact, Employee {
	@Column(unique = true)
	private String username;
	private String firstname;
	private String lastname;
	@ManyToOne
	private User manager;

	@SuppressWarnings("all")
	public String getUsername() {
		return this.username;
	}

	@SuppressWarnings("all")
	public String getFirstname() {
		return this.firstname;
	}

	@SuppressWarnings("all")
	public String getLastname() {
		return this.lastname;
	}

	@SuppressWarnings("all")
	public User getManager() {
		return this.manager;
	}

	@SuppressWarnings("all")
	public void setUsername(final String username) {
		this.username = username;
	}

	@SuppressWarnings("all")
	public void setFirstname(final String firstname) {
		this.firstname = firstname;
	}

	@SuppressWarnings("all")
	public void setLastname(final String lastname) {
		this.lastname = lastname;
	}

	@SuppressWarnings("all")
	public void setManager(final User manager) {
		this.manager = manager;
	}
}
